apiVersion: v1
kind: Service
metadata:
  name: stored-data
  labels:
    app: stored-data
    type: service
spec:
  selector:
    app: stored-data
    type: worker
  ports:
    - port: 8081
      targetPort: 8081
  clusterIP: None
